version: '3.9'

services:
  angie:
    image: angie/angie:latest
    container_name: angie
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./angie/angie.conf:/etc/angie/angie.conf:ro
      - ./www:/var/www/html
      - acme-data:/etc/angie/acme

volumes:
  acme-data:
